# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendinBlueSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(blank=True, help_text='You can retrieve your SendInBlue API Key <a target="_blank" href="https://my.sendinblue.com/advanced/apikey">here</a>', max_length=255, null=True, verbose_name='API Key')),
                ('automation', models.CharField(blank=True, help_text='You can retrieve your SendInBlue Automation API Key <a target="_blank" href="https://automation.sendinblue.com/parameters">here</a>', max_length=255, null=True, verbose_name='Automation API Key')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'SendInBlue',
            },
        ),
    ]
