# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import sendinblue.forms
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sendinblue', '0002_form_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendinblueform',
            name='confirm_template',
            field=models.IntegerField(blank=True, help_text='Send a confirmation mail to the user using this template', null=True, verbose_name='Confirmation template'),
        ),
        migrations.AddField(
            model_name='sendinblueform',
            name='notify_template',
            field=models.IntegerField(blank=True, help_text='Send a notification mail using this template. The notify mail should be defined in SendInBlue settings', null=True, verbose_name='Notify template'),
        ),
        migrations.AddField(
            model_name='sendinbluesettings',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='Notification mail will be sent to this email', max_length=255, null=True, verbose_name='Notification email'),
        ),
        migrations.AlterField(
            model_name='sendinblueform',
            name='definition',
            field=wagtail.wagtailcore.fields.StreamField((('text_field', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(help_text='The text displayed aside the field', label='Label', max_length=255, required=False)), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=True, label='Required', required=False)), ('attribute', sendinblue.forms.SendInBlueAttributeBlock(required=True)), ('placeholder', wagtail.wagtailcore.blocks.CharBlock(help_text='The text displayed inside the field when empty', label='Placeholder', max_length=255, required=False))))), ('textarea', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(help_text='The text displayed aside the field', label='Label', max_length=255, required=False)), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=True, label='Required', required=False)), ('rows', wagtail.wagtailcore.blocks.IntegerBlock(default=3, label='Rows', required=True)), ('attribute', wagtail.wagtailcore.blocks.CharBlock(default='message', help_text='The attribute used for transactional template', label='Attribute', max_length=255, required=True)), ('placeholder', wagtail.wagtailcore.blocks.CharBlock(help_text='The text displayed inside the field when empty', label='Placeholder', max_length=255, required=False))))), ('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
    ]
